# For local development only
services:
  redis:
    ports: [ "6379:6379" ]

  web:
    image: loltierlist-web:dev
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    pull_policy: never
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"

  worker:
    image: loltierlist-worker:dev
    build:
      context: .
      dockerfile: src/Worker/Dockerfile
    pull_policy: never
    environment:
      DOTNET_ENVIRONMENT: "Development"

  redisinsight:
    image: redis/redisinsight:2.70
    ports:
      - "5540:5540"
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./.devdata/redisinsight:/data
    restart: unless-stopped
    environment:
      RI_REDIS_HOST: redis
      RI_REDIS_PORT: 6379